---
- hosts: server
  remote_user: kaotu
  become: yes
  gather_facts: false

  tasks:
  - name: Install dependency of wordpress
    yum:
      name:
       - httpd
       - mariadb
       - mariadb-server
       - php 
       - php-common 
       - php-mysql 
       - php-gd 
       - php-xml 
       - php-mbstring
       - php-mcrypt 
       - php-xmlrpc 
       - unzip 
       - wget
      state: installed

  - name: Start and Enable service httpd
    service: 
      name: httpd
      state: started
      enabled: yes

  - name: Start and Enable service mariadb
    service: 
      name: mariadb
      state: started
      enabled: yes
    
  - name: Add firewall for http
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes 
 
  - name: Install pip
    yum:
     name: python-pip
     state: present

  - name: Install The PyMySQL
    pip: 
      name: PyMySQL

  - name: Set password for root
    mysql_user:
      login_user: root
      login_password: abc
      name: root
      password: abc
 
  - name: Removes anonymous user account for localhost
    mysql_user:
      login_user: root
      login_password: abc
      name: ''
      state: absent

  - name: Removes all anonymous user accounts
    mysql_user:
      login_user: root
      login_password: abc
      name: ''
      host_all: yes
      state: absent

  - name: Delete database with name 'test'
    mysql_db:
      login_user: root
      login_password: abc
      name: 
        - test
        - test*
      state: absent 
 
  - name: Create database with name 'WordPress'
    mysql_db:
      login_user: root
      login_password: abc
      name: wordpress 
      state: present
    
  - name: Add user ansible
    mysql_user:
      login_user: root
      login_password: abc
      name: ansible
      password: mypassword
      priv: 'wordpress.*:ALL'
 
  - name: Unzip tar wordpress file
    unarchive:
      src: https://wordpress.org/wordpress-5.0.tar.gz
      dest: /var/www/html
      remote_src: yes

  - name: Change file ownership, group and permissions
    file:
      path: /var/www/html/wordpress
      owner: apache
      group: apache
      mode: '0755'
      recurse: yes

  - name: Create uploads directory
    file: 
      path: /var/www/html/wordpress/wp-content/uploads
      group: apache
      recurse: yes

  - name: Set wp-config
    copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
      owner: apache
      group: apache
      mode: '0755'
      remote_src: yes

  - name: Replace DB_NAME
    lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      line: define('DB_NAME', 'wordpress');
      owner: apache
      group: apache
      mode: '0755'
  
  - name: Replace DB_USER
    lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'username_here'
      line: define('DB_USER', 'ansible');
      owner: apache
      group: apache
      mode: '0755'

  - name: Replace DB_PASSWORD
    lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'password_here'
      line: define('DB_PASSWORD', 'mypassword');
      owner: apache
      group: apache
      mode: '0755'
